version: '3.9'
services:
#  webserver:
#    image: ${account}.dkr.ecr.${region}.amazonaws.com/dashboard/webserver:${TAG:-latest}
#    build:
#      target: deploy

  php:
    image: ghcr.io/${ACCOUNT}/php:${TAG:-latest}
    build:
      target: deploy
