version: '3.9'
services:
  webserver:
    build:
      context: .
      dockerfile: './.docker/webserver/Dockerfile'
    ports:
      - '8081:80'
  php:
    build:
      context: .
      target: base
      dockerfile: './.docker/php/Dockerfile'

