version: "3.9"
services:
  composer:
    image: library/composer:2
    working_dir: /application
    volumes:
      - ./:/application
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    user: "${UID:-1000}:${GID:-1000}"
