version: '3.9'
services:
  webserver:
    image: ghcr.io/${ACCOUNT}/webserver:${TAG:-latest}
    build:
      context: .
      dockerfile: './.docker/webserver/Dockerfile'

  php:
    image: ghcr.io/${ACCOUNT}/php:${TAG:-latest}
    build:
      target: deploy
