version: '3.9'
services:
  php:
    build:
      context: .
      dockerfile: './.docker/php/Dockerfile'
    working_dir: /application
    command: ["bin/cake", "server", "-H", "0.0.0.0"]
    volumes:
      - ./:/application
    ports:
      - "8765:8765"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'inhouse-example'
    volumes:
      - ./.docker/data/db:/var/lib/mysql

  test-db:
    image: mysql:8
    tmpfs:
      /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'inhouse-example'

