version: '3.9'
services:
  webserver:
    image: ghcr.io/${ACCOUNT}/webserver:${TAG:-latest}
  php:
    image: ghcr.io/${ACCOUNT}/php:${TAG:-latest}
    build:
      target: deploy
    environment:
      SECURITY_SALT: cpwtq871ulgrpovmqctpvocty7mgofolpng3duca71xikas6b5c27s825b0nk42z
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: inhouse-example
