version: '3.9'
services:
  php:
    build:
      context: .
      target: base
      dockerfile: './.docker/php/Dockerfile'
    working_dir: /application
    command: ["bin/cake", "server", "-H", "0.0.0.0"]
    volumes:
      - ./:/application
    ports:
      - "8765:8765"

