#!/bin/bash
# strta/setup: Set up application for the first time after cloning.
set -euo pipefail
shopt -s inherit_errexit
PROJECT_ROOT=$(git rev-parse --show-toplevel)

rm -rf "${PROJECT_ROOT}/vendor"
rm -rf "${PROJECT_ROOT}/scripts/node_modules"


echo "==> Installing composer dependencies…"
docker compose -f docker-compose.setup.yml run --rm composer install

echo "==> Installing yarn dependencies…"
docker compose -f docker-compose.setup.yml run --rm yarn install

echo "==> Building assets…"
docker compose -f docker-compose.setup.yml run --rm yarn run build

echo "==> Building docker containers…"
docker compose build

echo "==> App is now ready to go!"
