#!/bin/bash
# strta/test: Run test suite for application.
set -euo pipefail
shopt -s inherit_errexit
PROJECT_ROOT=$(git rev-parse --show-toplevel)

docker compose up -d test-db
while ! docker compose exec test-db mysqladmin ping -s -h test-db;
do
  echo waiting for database; sleep 1;
done;

echo "==> Running tests…"
docker compose run --rm php composer test
echo "==> Testing is now done!"
