name: Continuous Integration and Deployment

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      UID: 1001 # Runner
      GID: 121  # Docker
    steps:
    - uses: actions/checkout@v3
    - name: Build containers for testing
      run: ./strta/setup
    - name: Run tests
      run: ./strta/test
  Deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [Test]
    env:
      UID: 1001 # Runner
      GID: 121  # Docker
    steps:
      - uses: actions/checkout@v3
      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build images and push
        run: |
          export ACCOUNT=$(echo "${{ github.repository_owner }}" | tr '[A-Z]' '[a-z]')
          export TAG=${{ github.sha }}
          ./strta/cdbuild
          export TAG=latest
          ./strta/cdbuild
      - name: Pull images on production
        run: |
          export JWT=$(curl -X POST --location "https://portainer.test-easy-lms.com/api/auth" -H "Content-Type: Application/json" -d "{\"Username\": \"$PORTAINER_USER\", \"Password\": \"$PORTAINER_PASSWORD\"}" | jq -r .jwt)
          curl -X PUT --location "https://portainer.test-easy-lms.com/api/stacks/9/git/redeploy?endpointId=2" \
            -H "Authorization: Bearer $JWT" \
            -H "Content-Type: application/json" \
            -d "{
            \"env\": [],
            \"prune\": false,
            \"RepositoryReferenceName\": \"refs/heads/master\",
            \"RepositoryAuthentication\": true,
            \"RepositoryUsername\": \"mkraijenoord\",
            \"RepositoryPassword\": \"\",
            \"PullImage\": true
          }"

