name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  testsuite:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        ./strta/build

    - name: Tests
      run: |
        ./strta/test
