name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build & run tests
      run: |
        ./strta/setup
        ./strta/test
