name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    env:
      UID: 1001 # Runner
      GID: 121  # Docker
    steps:
    - uses: actions/checkout@v3
    - name: Build containers for testing
      run: ./strta/setup
    - name: Run tests
      run: ./strta/test
